import {
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";
import { dark } from "@mui/material/styles/createPalette";
import React from "react";

const DataTable1 = [
  {
    id: 1,
    first_name: "Rhody",
    last_name: "Ilyushkin",
    email: "rilyushkin0@photobucket.com",
    gender: "Female",
    ip_address: "42.229.144.206",
  },
  {
    id: 2,
    first_name: "Panchito",
    last_name: "Hawkings",
    email: "phawkings1@wordpress.org",
    gender: "Male",
    ip_address: "178.98.218.148",
  },
  {
    id: 3,
    first_name: "Cyb",
    last_name: "Robottham",
    email: "crobottham2@odnoklassniki.ru",
    gender: "Female",
    ip_address: "172.142.185.84",
  },
  {
    id: 4,
    first_name: "Giorgio",
    last_name: "Antalffy",
    email: "gantalffy3@vimeo.com",
    gender: "Male",
    ip_address: "53.160.100.204",
  },
  {
    id: 5,
    first_name: "Decca",
    last_name: "Merwood",
    email: "dmerwood4@shop-pro.jp",
    gender: "Male",
    ip_address: "190.229.214.238",
  },
  {
    id: 6,
    first_name: "Jodee",
    last_name: "Banfill",
    email: "jbanfill5@oaic.gov.au",
    gender: "Female",
    ip_address: "91.70.19.55",
  },
  {
    id: 7,
    first_name: "Zacharia",
    last_name: "Rizziello",
    email: "zrizziello6@so-net.ne.jp",
    gender: "Male",
    ip_address: "78.35.148.202",
  },
  {
    id: 8,
    first_name: "Lonny",
    last_name: "Halfacree",
    email: "lhalfacree7@arizona.edu",
    gender: "Male",
    ip_address: "132.169.90.24",
  },
  {
    id: 9,
    first_name: "Frederigo",
    last_name: "Sleight",
    email: "fsleight8@sciencedirect.com",
    gender: "Genderfluid",
    ip_address: "30.161.129.159",
  },
  {
    id: 10,
    first_name: "Bernhard",
    last_name: "Liven",
    email: "bliven9@rakuten.co.jp",
    gender: "Genderqueer",
    ip_address: "201.117.62.52",
  },
  {
    id: 11,
    first_name: "Sterne",
    last_name: "Dorie",
    email: "sdoriea@google.com.hk",
    gender: "Male",
    ip_address: "35.202.8.34",
  },
  {
    id: 12,
    first_name: "Bear",
    last_name: "Abbotts",
    email: "babbottsb@cbsnews.com",
    gender: "Male",
    ip_address: "223.87.19.52",
  },
  {
    id: 13,
    first_name: "Valene",
    last_name: "Nehl",
    email: "vnehlc@fema.gov",
    gender: "Female",
    ip_address: "6.27.150.123",
  },
  {
    id: 14,
    first_name: "Prentice",
    last_name: "Hawkeswood",
    email: "phawkeswoodd@g.co",
    gender: "Male",
    ip_address: "84.1.123.164",
  },
  {
    id: 15,
    first_name: "Edward",
    last_name: "Diche",
    email: "edichee@hibu.com",
    gender: "Male",
    ip_address: "141.48.55.154",
  },
  {
    id: 16,
    first_name: "Perkin",
    last_name: "Clerk",
    email: "pclerkf@unesco.org",
    gender: "Male",
    ip_address: "79.13.217.70",
  },
  {
    id: 17,
    first_name: "Friedrick",
    last_name: "Aldie",
    email: "faldieg@thetimes.co.uk",
    gender: "Male",
    ip_address: "181.179.74.17",
  },
  {
    id: 18,
    first_name: "Clywd",
    last_name: "Brunsden",
    email: "cbrunsdenh@slate.com",
    gender: "Male",
    ip_address: "177.127.96.59",
  },
  {
    id: 19,
    first_name: "Kalli",
    last_name: "Lailey",
    email: "klaileyi@japanpost.jp",
    gender: "Female",
    ip_address: "43.144.54.206",
  },
  {
    id: 20,
    first_name: "Gwen",
    last_name: "Jandourek",
    email: "gjandourekj@51.la",
    gender: "Female",
    ip_address: "68.69.187.150",
  },
  {
    id: 21,
    first_name: "Kennedy",
    last_name: "Shilton",
    email: "kshiltonk@t-online.de",
    gender: "Male",
    ip_address: "109.183.32.69",
  },
  {
    id: 22,
    first_name: "Swen",
    last_name: "Allridge",
    email: "sallridgel@tiny.cc",
    gender: "Male",
    ip_address: "164.7.134.26",
  },
  {
    id: 23,
    first_name: "Hieronymus",
    last_name: "Hablet",
    email: "hhabletm@nih.gov",
    gender: "Male",
    ip_address: "199.225.212.37",
  },
  {
    id: 24,
    first_name: "Timotheus",
    last_name: "Linfoot",
    email: "tlinfootn@altervista.org",
    gender: "Male",
    ip_address: "184.51.165.158",
  },
  {
    id: 25,
    first_name: "Paten",
    last_name: "Eyrl",
    email: "peyrlo@ftc.gov",
    gender: "Male",
    ip_address: "198.227.79.135",
  },
  {
    id: 26,
    first_name: "Felecia",
    last_name: "Lumbly",
    email: "flumblyp@buzzfeed.com",
    gender: "Female",
    ip_address: "165.55.128.9",
  },
  {
    id: 27,
    first_name: "Lindsy",
    last_name: "Heikkinen",
    email: "lheikkinenq@walmart.com",
    gender: "Female",
    ip_address: "95.121.133.112",
  },
  {
    id: 28,
    first_name: "Gerti",
    last_name: "Giannasi",
    email: "ggiannasir@ox.ac.uk",
    gender: "Female",
    ip_address: "153.225.88.63",
  },
  {
    id: 29,
    first_name: "Norrie",
    last_name: "Treece",
    email: "ntreeces@utexas.edu",
    gender: "Female",
    ip_address: "110.173.171.141",
  },
  {
    id: 30,
    first_name: "Rochell",
    last_name: "Wellings",
    email: "rwellingst@51.la",
    gender: "Female",
    ip_address: "11.215.255.89",
  },
  {
    id: 31,
    first_name: "Jeanelle",
    last_name: "Peterken",
    email: "jpeterkenu@prnewswire.com",
    gender: "Female",
    ip_address: "237.238.98.47",
  },
  {
    id: 32,
    first_name: "Sascha",
    last_name: "MacAvddy",
    email: "smacavddyv@elegantthemes.com",
    gender: "Female",
    ip_address: "65.41.56.80",
  },
  {
    id: 33,
    first_name: "Leonore",
    last_name: "Thacker",
    email: "lthackerw@phoca.cz",
    gender: "Female",
    ip_address: "172.203.152.48",
  },
  {
    id: 34,
    first_name: "Nickie",
    last_name: "Quilligan",
    email: "nquilliganx@slideshare.net",
    gender: "Male",
    ip_address: "125.215.234.33",
  },
  {
    id: 35,
    first_name: "Onida",
    last_name: "Tooze",
    email: "otoozey@trellian.com",
    gender: "Female",
    ip_address: "132.47.220.50",
  },
  {
    id: 36,
    first_name: "Danit",
    last_name: "Sager",
    email: "dsagerz@wunderground.com",
    gender: "Female",
    ip_address: "239.16.122.153",
  },
  {
    id: 37,
    first_name: "Katrina",
    last_name: "Pleven",
    email: "kpleven10@ihg.com",
    gender: "Female",
    ip_address: "179.106.220.44",
  },
  {
    id: 38,
    first_name: "Weston",
    last_name: "Spurrett",
    email: "wspurrett11@google.nl",
    gender: "Male",
    ip_address: "203.94.230.164",
  },
  {
    id: 39,
    first_name: "Mario",
    last_name: "Jaskowicz",
    email: "mjaskowicz12@earthlink.net",
    gender: "Male",
    ip_address: "129.96.201.51",
  },
  {
    id: 40,
    first_name: "Codie",
    last_name: "Astling",
    email: "castling13@netscape.com",
    gender: "Male",
    ip_address: "191.254.187.49",
  },
  {
    id: 41,
    first_name: "Sherwood",
    last_name: "Marcham",
    email: "smarcham14@paginegialle.it",
    gender: "Male",
    ip_address: "56.185.31.171",
  },
  {
    id: 42,
    first_name: "Daffie",
    last_name: "Claibourn",
    email: "dclaibourn15@prweb.com",
    gender: "Female",
    ip_address: "209.49.147.204",
  },
  {
    id: 43,
    first_name: "Valma",
    last_name: "Haly",
    email: "vhaly16@wired.com",
    gender: "Female",
    ip_address: "69.151.230.183",
  },
  {
    id: 44,
    first_name: "Jacob",
    last_name: "St. Louis",
    email: "jstlouis17@a8.net",
    gender: "Male",
    ip_address: "127.101.194.239",
  },
  {
    id: 45,
    first_name: "Bibby",
    last_name: "Pownall",
    email: "bpownall18@fc2.com",
    gender: "Non-binary",
    ip_address: "244.172.41.53",
  },
  {
    id: 46,
    first_name: "Andreas",
    last_name: "McNelis",
    email: "amcnelis19@msu.edu",
    gender: "Male",
    ip_address: "92.90.165.56",
  },
  {
    id: 47,
    first_name: "Kalli",
    last_name: "Lafflin",
    email: "klafflin1a@latimes.com",
    gender: "Female",
    ip_address: "69.193.192.162",
  },
  {
    id: 48,
    first_name: "Alicia",
    last_name: "de Savery",
    email: "adesavery1b@bigcartel.com",
    gender: "Female",
    ip_address: "161.171.172.4",
  },
  {
    id: 49,
    first_name: "Darnall",
    last_name: "Bessom",
    email: "dbessom1c@ow.ly",
    gender: "Male",
    ip_address: "48.179.196.158",
  },
  {
    id: 50,
    first_name: "Leila",
    last_name: "Springle",
    email: "lspringle1d@arizona.edu",
    gender: "Genderqueer",
    ip_address: "143.43.176.46",
  },
];

const MuiTable = () => {
  return (
    <TableContainer component={Paper} sx={{ maxHeight: "300px" }}>
      <Table aria-aria-label="simple table" stickyHeader>
        <TableHead>
          <TableRow>
            <TableCell>Id</TableCell>
            <TableCell>First Name</TableCell>
            <TableCell>Last Name</TableCell>
            <TableCell align="center">Email</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {DataTable1.map((row) => (
            <TableRow key={row.id} sx={{ "&:last-child td , &:last-child th": { border: 0 } }}>
              <TableCell>{row.id}</TableCell>
              <TableCell>{row.first_name}</TableCell>
              <TableCell>{row.last_name}</TableCell>
              <TableCell align="center">{row.email}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};

export default MuiTable;
